name: cleanup caches on main

# Configure Manual Trigger
on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        run: |
          printf "Fetching list of cache key\n"
          cacheKeysForPR=$(gh cache list)

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          printf "Deleting caches...\n"
          for cacheKey in $cacheKeysForPR
          do
              printf "$cacheKey\n"
              gh cache delete $cacheKey
          done
          printf "Done\n"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
